//! Traefik sidecar lifecycle: render compose + static config, start/stop/
//! status/logs via `docker compose`.
//!
//! Per ADR-0005 each unique project port becomes a Traefik entryPoint
//! `port-<port>` that binds on the host. Static config is generated on
//! `start` from the union of ports across all active sandboxes (caller
//! collects them; this module only renders + drives docker compose).
//!
//! Render outputs (under `$XDG_DATA_HOME/sandbox/proxy/`):
//!
//! - `docker-compose.yml` — the Traefik service definition.
//! - `traefik.yaml`       — static config: entryPoints + providers.
//!
//! Both files are regenerated on each `start` invocation so they stay in
//! sync with the current port universe.

use std::path::{Path, PathBuf};

use crate::{Error, Result};

/// Network the proxy and project containers share. Created by docker
/// compose on first `start`.
pub const PROXY_NETWORK: &str = "sandbox-proxy";

/// Compose project name (controls container prefix). Constant so `docker
/// compose -p` lookups are reproducible.
pub const COMPOSE_PROJECT: &str = "sandbox-proxy";

/// Default Traefik dashboard port. Out of the way of common dev ports.
pub const DASHBOARD_PORT: u16 = 8090;

/// Configuration for one `start` invocation. The proxy is regenerated each
/// time so changes here take effect on the next call.
#[derive(Debug, Clone, Default)]
pub struct ProxyConfig {
    /// Host ports to expose as Traefik entryPoints. One entryPoint per port,
    /// each named `port-<port>` (matches the labels produced by
    /// [`crate::labels`]).
    pub ports: Vec<u16>,
    /// When true, enable the Traefik dashboard on `DASHBOARD_PORT`.
    pub dashboard: bool,
}

/// Write `docker-compose.yml` and `traefik.yaml` under `proxy_dir`. Returns
/// the compose file path so the caller can pass it to `docker compose -f`.
pub fn render(proxy_dir: &Path, cfg: &ProxyConfig) -> Result<PathBuf> {
    std::fs::create_dir_all(proxy_dir).map_err(|source| Error::Io {
        path: proxy_dir.to_path_buf(),
        source,
    })?;
    let traefik_yaml = proxy_dir.join("traefik.yaml");
    std::fs::write(&traefik_yaml, render_static_config(cfg)).map_err(|source| Error::Io {
        path: traefik_yaml.clone(),
        source,
    })?;
    let compose_yml = proxy_dir.join("docker-compose.yml");
    std::fs::write(&compose_yml, render_compose(cfg)).map_err(|source| Error::Io {
        path: compose_yml.clone(),
        source,
    })?;
    Ok(compose_yml)
}

fn render_static_config(cfg: &ProxyConfig) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by `sandbox proxy start`. Do not edit by hand.\n");
    out.push_str("# See docs/sandbox/adrs/0005-reverse-proxy-traefik.md.\n\n");

    out.push_str("entryPoints:\n");
    for port in &cfg.ports {
        out.push_str(&format!("  port-{port}:\n"));
        out.push_str(&format!("    address: \":{port}\"\n"));
    }
    if cfg.dashboard {
        out.push_str(&format!(
            "  dashboard:\n    address: \":{DASHBOARD_PORT}\"\n"
        ));
    }
    out.push('\n');

    out.push_str("providers:\n");
    out.push_str("  docker:\n");
    out.push_str(&format!("    network: {PROXY_NETWORK}\n"));
    out.push_str("    exposedByDefault: false\n");
    out.push('\n');

    if cfg.dashboard {
        out.push_str("api:\n  dashboard: true\n  insecure: true\n\n");
    }

    out.push_str("log:\n  level: INFO\n");
    out.push_str("accessLog: {}\n");
    out
}

fn render_compose(cfg: &ProxyConfig) -> String {
    let mut ports_yaml = String::new();
    for port in &cfg.ports {
        ports_yaml.push_str(&format!("      - \"{port}:{port}\"\n"));
    }
    if cfg.dashboard {
        ports_yaml.push_str(&format!("      - \"{DASHBOARD_PORT}:{DASHBOARD_PORT}\"\n"));
    }
    let ports_block = if ports_yaml.is_empty() {
        // No project ports yet — still bring up Traefik so the user can run
        // `sandbox run` afterwards and re-`proxy start` to register them.
        String::new()
    } else {
        format!("    ports:\n{ports_yaml}")
    };
    format!(
        "# Auto-generated by `sandbox proxy start`. Do not edit by hand.\n\
         name: {COMPOSE_PROJECT}\n\
         \n\
         services:\n\
         \x20\x20traefik:\n\
         \x20\x20\x20\x20image: traefik:v3.1\n\
         \x20\x20\x20\x20container_name: {COMPOSE_PROJECT}\n\
         \x20\x20\x20\x20restart: unless-stopped\n\
         {ports_block}\
         \x20\x20\x20\x20volumes:\n\
         \x20\x20\x20\x20\x20\x20- ./traefik.yaml:/etc/traefik/traefik.yaml:ro\n\
         \x20\x20\x20\x20\x20\x20- /var/run/docker.sock:/var/run/docker.sock:ro\n\
         \x20\x20\x20\x20networks:\n\
         \x20\x20\x20\x20\x20\x20- {PROXY_NETWORK}\n\
         \n\
         networks:\n\
         \x20\x20{PROXY_NETWORK}:\n\
         \x20\x20\x20\x20name: {PROXY_NETWORK}\n",
    )
}

/// Whether the proxy container is currently running.
pub async fn is_running() -> Result<bool> {
    let output = tokio::process::Command::new("docker")
        .args([
            "ps",
            "--quiet",
            "--filter",
            &format!("name=^{COMPOSE_PROJECT}$"),
        ])
        .output()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker ps probe: {e}")))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(Error::TraefikLifecycle(format!(
            "docker ps failed: {stderr}"
        )));
    }
    Ok(!output.stdout.is_empty())
}

/// `docker compose -f <compose_file> up -d`.
pub async fn start(compose_file: &Path) -> Result<()> {
    compose_run(compose_file, &["up", "-d"]).await
}

/// `docker compose -f <compose_file> down`.
pub async fn stop(compose_file: &Path) -> Result<()> {
    compose_run(compose_file, &["down"]).await
}

/// `docker compose -f <compose_file> ps` (captured stdout).
pub async fn status(compose_file: &Path) -> Result<String> {
    compose_capture(compose_file, &["ps"]).await
}

/// `docker compose -f <compose_file> logs [-f]`. Stream attached when
/// `follow=true`, captured otherwise (use `--tail N` if needed; deferred).
pub async fn logs(compose_file: &Path, follow: bool) -> Result<()> {
    let mut args: Vec<&str> = vec!["logs"];
    if follow {
        args.push("--follow");
    }
    compose_run(compose_file, &args).await
}

async fn compose_run(compose_file: &Path, subcmd: &[&str]) -> Result<()> {
    let compose_str = compose_file
        .to_str()
        .ok_or_else(|| Error::TraefikLifecycle("compose path not utf-8".into()))?;
    let mut args = vec!["compose", "-f", compose_str];
    args.extend_from_slice(subcmd);
    let status = tokio::process::Command::new("docker")
        .args(&args)
        .status()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker compose {:?}: {e}", subcmd)))?;
    if !status.success() {
        return Err(Error::TraefikLifecycle(format!(
            "docker compose {} exited with {}",
            subcmd.join(" "),
            status.code().unwrap_or(-1),
        )));
    }
    Ok(())
}

async fn compose_capture(compose_file: &Path, subcmd: &[&str]) -> Result<String> {
    let compose_str = compose_file
        .to_str()
        .ok_or_else(|| Error::TraefikLifecycle("compose path not utf-8".into()))?;
    let mut args = vec!["compose", "-f", compose_str];
    args.extend_from_slice(subcmd);
    let output = tokio::process::Command::new("docker")
        .args(&args)
        .output()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker compose {:?}: {e}", subcmd)))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(Error::TraefikLifecycle(format!(
            "docker compose {} failed: {stderr}",
            subcmd.join(" "),
        )));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestResult = std::result::Result<(), Box<dyn std::error::Error>>;

    #[test]
    fn render_static_config_emits_one_entrypoint_per_port() {
        let s = render_static_config(&ProxyConfig {
            ports: vec![3000, 5007],
            dashboard: false,
        });
        assert!(s.contains("port-3000:\n"));
        assert!(s.contains("port-5007:\n"));
        assert!(s.contains("address: \":3000\""));
        assert!(s.contains("address: \":5007\""));
        // No dashboard block when disabled.
        assert!(!s.contains("dashboard:\n"));
    }

    #[test]
    fn render_static_config_with_dashboard() {
        let s = render_static_config(&ProxyConfig {
            ports: vec![3000],
            dashboard: true,
        });
        assert!(s.contains("dashboard:\n"));
        assert!(s.contains(&format!("address: \":{DASHBOARD_PORT}\"")));
        assert!(s.contains("api:\n"));
    }

    #[test]
    fn render_compose_publishes_each_port_to_host() {
        let s = render_compose(&ProxyConfig {
            ports: vec![3000, 5007],
            dashboard: false,
        });
        assert!(s.contains(&format!("name: {COMPOSE_PROJECT}\n")));
        assert!(s.contains("\"3000:3000\""));
        assert!(s.contains("\"5007:5007\""));
        assert!(s.contains(&format!("name: {PROXY_NETWORK}")));
    }

    #[test]
    fn render_compose_with_no_ports_skips_ports_block() {
        let s = render_compose(&ProxyConfig {
            ports: vec![],
            dashboard: false,
        });
        assert!(!s.contains("ports:"));
    }

    #[test]
    fn render_writes_both_files_under_proxy_dir() -> TestResult {
        let tmp = tempfile::tempdir()?;
        let cfg = ProxyConfig {
            ports: vec![3000],
            dashboard: true,
        };
        let compose = render(tmp.path(), &cfg)?;
        assert!(compose.is_file());
        assert!(tmp.path().join("traefik.yaml").is_file());
        // Compose file points at the traefik.yaml we just wrote.
        let compose_body = std::fs::read_to_string(&compose)?;
        assert!(compose_body.contains("./traefik.yaml:/etc/traefik/traefik.yaml:ro"));
        Ok(())
    }
}
