//! Traefik sidecar lifecycle: render compose + static config, start/stop/
//! status/logs via `docker compose`.
//!
//! Per ADR-0005 each unique project port becomes a Traefik entryPoint
//! `port-<port>` that binds on the host. Static config is generated on
//! `start` from the union of ports across all active sandboxes (caller
//! collects them; this module only renders + drives docker compose).
//!
//! Render outputs (under `$XDG_DATA_HOME/sandbox/proxy/`):
//!
//! - `docker-compose.yml` — the Traefik service definition.
//! - `traefik.yaml`       — static config: entryPoints + providers.
//!
//! Both files are regenerated on each `start` invocation so they stay in
//! sync with the current port universe.

use std::path::{Path, PathBuf};

use crate::{Error, Result};

/// Network the proxy and project containers share. Created by docker
/// compose on first `start`.
pub const PROXY_NETWORK: &str = "sandbox-proxy";

/// Compose project name (controls container prefix). Constant so `docker
/// compose -p` lookups are reproducible.
pub const COMPOSE_PROJECT: &str = "sandbox-proxy";

/// Default Traefik dashboard port. Out of the way of common dev ports.
pub const DASHBOARD_PORT: u16 = 8090;

/// Configuration for one `start` invocation. The proxy is regenerated each
/// time so changes here take effect on the next call.
#[derive(Debug, Clone, Default)]
pub struct ProxyConfig {
    /// Host ports to expose as Traefik entryPoints. One entryPoint per port,
    /// each named `port-<port>` (matches the labels produced by
    /// [`crate::labels`]).
    pub ports: Vec<u16>,
    /// When true, enable the Traefik dashboard on `DASHBOARD_PORT`.
    pub dashboard: bool,
    /// Docker daemon API version (e.g. `1.45`) to pin via the
    /// `DOCKER_API_VERSION` env var. Without this, the moby client lib
    /// bundled in `traefik:v3.1` negotiates to 1.24 by default, which
    /// modern Docker daemons (>= 25) reject. Caller should query the
    /// daemon's `.Server.APIVersion` and pass it through.
    pub docker_api_version: Option<String>,
}

/// Write `docker-compose.yml`, `traefik.yaml`, and an empty `dynamic/` dir
/// under `proxy_dir`. Returns the compose file path so the caller can pass
/// it to `docker compose -f`. The caller is responsible for writing per-
/// project files into `dynamic/` via [`render_project_dynamic`] before
/// starting the proxy.
pub fn render(proxy_dir: &Path, cfg: &ProxyConfig) -> Result<PathBuf> {
    std::fs::create_dir_all(proxy_dir).map_err(|source| Error::Io {
        path: proxy_dir.to_path_buf(),
        source,
    })?;
    let dynamic_dir = proxy_dir.join("dynamic");
    std::fs::create_dir_all(&dynamic_dir).map_err(|source| Error::Io {
        path: dynamic_dir.clone(),
        source,
    })?;
    let traefik_yaml = proxy_dir.join("traefik.yaml");
    std::fs::write(&traefik_yaml, render_static_config(cfg)).map_err(|source| Error::Io {
        path: traefik_yaml.clone(),
        source,
    })?;
    let compose_yml = proxy_dir.join("docker-compose.yml");
    std::fs::write(&compose_yml, render_compose(cfg)).map_err(|source| Error::Io {
        path: compose_yml.clone(),
        source,
    })?;
    Ok(compose_yml)
}

/// Clear and repopulate `<proxy_dir>/dynamic/` from an iterator of
/// per-project tuples `(slug, container_name, ports)`. Wipes the directory
/// first so a removed project doesn't leak a stale route file. Returns the
/// list of slugs that ended up with a written file (skips projects with
/// empty `ports`).
pub fn write_dynamic_configs<I>(proxy_dir: &Path, projects: I, domain: &str) -> Result<Vec<String>>
where
    I: IntoIterator<Item = (String, String, Vec<u16>)>,
{
    let dynamic_dir = proxy_dir.join("dynamic");
    if dynamic_dir.exists() {
        std::fs::remove_dir_all(&dynamic_dir).map_err(|source| Error::Io {
            path: dynamic_dir.clone(),
            source,
        })?;
    }
    std::fs::create_dir_all(&dynamic_dir).map_err(|source| Error::Io {
        path: dynamic_dir.clone(),
        source,
    })?;
    let mut written = Vec::new();
    for (slug, container_name, ports) in projects {
        if ports.is_empty() {
            continue;
        }
        let body = render_project_dynamic(&slug, &container_name, &ports, domain);
        let path = dynamic_dir.join(format!("{slug}.yaml"));
        std::fs::write(&path, body).map_err(|source| Error::Io { path, source })?;
        written.push(slug);
    }
    Ok(written)
}

fn render_static_config(cfg: &ProxyConfig) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by `sandbox proxy start`. Do not edit by hand.\n");
    out.push_str("# See docs/sandbox/adrs/0005-reverse-proxy-traefik.md.\n\n");

    out.push_str("entryPoints:\n");
    for port in &cfg.ports {
        out.push_str(&format!("  port-{port}:\n"));
        out.push_str(&format!("    address: \":{port}\"\n"));
    }
    if cfg.dashboard {
        // Must be named `traefik` (not `dashboard`) so `api.insecure: true`
        // auto-attaches the dashboard + API routers to this entryPoint. With
        // any other name the auto-router has nowhere to bind and requests
        // here return 404 with no route matched. See Traefik docs on
        // `api.insecure`.
        out.push_str(&format!("  traefik:\n    address: \":{DASHBOARD_PORT}\"\n"));
    }
    out.push('\n');

    // File provider scans `/etc/traefik/dynamic/*.yaml` and re-reads on
    // change. We chose this over the docker provider because the bundled
    // moby client lib in `traefik:v3.x` negotiates a stale API version
    // (1.24) that modern Docker daemons (>= 25) reject — and because the
    // file provider also drops the docker.sock mount, which is a meaningful
    // security win for a reverse proxy that doesn't need it. The CLI
    // materializes one `dynamic/<slug>.yaml` per active sandbox from
    // `Meta::load_all()` on every `proxy start`.
    out.push_str("providers:\n");
    out.push_str("  file:\n");
    out.push_str("    directory: /etc/traefik/dynamic\n");
    out.push_str("    watch: true\n");
    out.push('\n');

    if cfg.dashboard {
        out.push_str("api:\n  dashboard: true\n  insecure: true\n\n");
    }

    out.push_str("log:\n  level: INFO\n");
    out.push_str("accessLog: {}\n");
    out
}

/// Render one dynamic-config block for a single project. Caller writes the
/// returned string to `<proxy_dir>/dynamic/<slug>.yaml`; Traefik picks it
/// up on next watch tick.
///
/// `container_name` must be reachable on the `sandbox-proxy` network — it's
/// the Docker DNS name (e.g. `sandbox-abc123def456`). Project containers
/// join that network via `Plan.additional_networks`, so the name resolves
/// from inside the Traefik container.
pub fn render_project_dynamic(
    slug: &str,
    container_name: &str,
    ports: &[u16],
    domain: &str,
) -> String {
    if ports.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    out.push_str("# Auto-generated by `sandbox proxy start`. Do not edit by hand.\n");
    out.push_str("http:\n");
    out.push_str("  routers:\n");
    for port in ports {
        let id = format!("sb-{slug}-{port}");
        out.push_str(&format!("    {id}:\n"));
        out.push_str(&format!("      rule: \"Host(`{slug}.{domain}`)\"\n"));
        out.push_str(&format!("      entryPoints: [\"port-{port}\"]\n"));
        out.push_str(&format!("      service: {id}\n"));
    }
    out.push_str("  services:\n");
    for port in ports {
        let id = format!("sb-{slug}-{port}");
        out.push_str(&format!("    {id}:\n"));
        out.push_str("      loadBalancer:\n");
        out.push_str("        servers:\n");
        out.push_str(&format!(
            "          - url: \"http://{container_name}:{port}\"\n"
        ));
    }
    out
}

fn render_compose(cfg: &ProxyConfig) -> String {
    let mut ports_yaml = String::new();
    for port in &cfg.ports {
        ports_yaml.push_str(&format!("      - \"{port}:{port}\"\n"));
    }
    if cfg.dashboard {
        ports_yaml.push_str(&format!("      - \"{DASHBOARD_PORT}:{DASHBOARD_PORT}\"\n"));
    }
    let ports_block = if ports_yaml.is_empty() {
        // No project ports yet — still bring up Traefik so the user can run
        // `sandbox run` afterwards and re-`proxy start` to register them.
        String::new()
    } else {
        format!("    ports:\n{ports_yaml}")
    };
    // File provider only — no docker.sock mount needed. `dynamic/` is
    // populated by the CLI from `Meta::load_all()` on every `proxy start`.
    //
    // Traefik is dual-homed (ADR-0004):
    //  - `default`: compose's auto-created bridge. Carries Traefik's published
    //    host ports (`-p`) and its own egress. Published ports do NOT work on
    //    an `--internal` network, so Traefik needs this egress-capable one.
    //  - `sandbox-proxy`: the `--internal` network the sandboxes sit on.
    //    Routing host→Traefik→sandbox is container-to-container here, with no
    //    egress for the sandboxes themselves.
    // `sandbox-proxy` is declared `external` so compose references the
    // pre-existing network (created `--internal` by `ensure_internal` from
    // `sandbox run` / `proxy start`) instead of trying to adopt it and
    // aborting the `up`.
    let _ = &cfg.docker_api_version; // No longer needed with file provider.
    format!(
        "# Auto-generated by `sandbox proxy start`. Do not edit by hand.\n\
         name: {COMPOSE_PROJECT}\n\
         \n\
         services:\n\
         \x20\x20traefik:\n\
         \x20\x20\x20\x20image: traefik:v3.5\n\
         \x20\x20\x20\x20container_name: {COMPOSE_PROJECT}\n\
         \x20\x20\x20\x20restart: unless-stopped\n\
         {ports_block}\
         \x20\x20\x20\x20volumes:\n\
         \x20\x20\x20\x20\x20\x20- ./traefik.yaml:/etc/traefik/traefik.yaml:ro\n\
         \x20\x20\x20\x20\x20\x20- ./dynamic:/etc/traefik/dynamic:ro\n\
         \x20\x20\x20\x20networks:\n\
         \x20\x20\x20\x20\x20\x20- default\n\
         \x20\x20\x20\x20\x20\x20- {PROXY_NETWORK}\n\
         \n\
         networks:\n\
         \x20\x20{PROXY_NETWORK}:\n\
         \x20\x20\x20\x20name: {PROXY_NETWORK}\n\
         \x20\x20\x20\x20external: true\n",
    )
}

/// Query the local daemon's API version (e.g. `"1.51"`) so the caller can
/// pin it via `DOCKER_API_VERSION` on the Traefik container. Without
/// pinning, the moby client lib inside `traefik:v3.1` negotiates to a
/// stale 1.24 that modern daemons reject.
pub async fn detect_docker_api_version() -> Result<String> {
    let output = tokio::process::Command::new("docker")
        .args(["version", "--format", "{{.Server.APIVersion}}"])
        .output()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker version: {e}")))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(Error::TraefikLifecycle(format!(
            "docker version failed: {stderr}"
        )));
    }
    let v = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if v.is_empty() {
        return Err(Error::TraefikLifecycle(
            "docker version returned empty server API version".into(),
        ));
    }
    Ok(v)
}

/// Whether the proxy container is currently running.
pub async fn is_running() -> Result<bool> {
    let output = tokio::process::Command::new("docker")
        .args([
            "ps",
            "--quiet",
            "--filter",
            &format!("name=^{COMPOSE_PROJECT}$"),
        ])
        .output()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker ps probe: {e}")))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(Error::TraefikLifecycle(format!(
            "docker ps failed: {stderr}"
        )));
    }
    Ok(!output.stdout.is_empty())
}

/// `docker compose -f <compose_file> up -d`.
pub async fn start(compose_file: &Path) -> Result<()> {
    compose_run(compose_file, &["up", "-d"]).await
}

/// `docker compose -f <compose_file> down`.
pub async fn stop(compose_file: &Path) -> Result<()> {
    compose_run(compose_file, &["down"]).await
}

/// `docker compose -f <compose_file> ps` (captured stdout).
pub async fn status(compose_file: &Path) -> Result<String> {
    compose_capture(compose_file, &["ps"]).await
}

/// `docker compose -f <compose_file> logs [-f]`. Stream attached when
/// `follow=true`, captured otherwise (use `--tail N` if needed; deferred).
pub async fn logs(compose_file: &Path, follow: bool) -> Result<()> {
    let mut args: Vec<&str> = vec!["logs"];
    if follow {
        args.push("--follow");
    }
    compose_run(compose_file, &args).await
}

async fn compose_run(compose_file: &Path, subcmd: &[&str]) -> Result<()> {
    let compose_str = compose_file
        .to_str()
        .ok_or_else(|| Error::TraefikLifecycle("compose path not utf-8".into()))?;
    let mut args = vec!["compose", "-f", compose_str];
    args.extend_from_slice(subcmd);
    let status = tokio::process::Command::new("docker")
        .args(&args)
        .status()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker compose {:?}: {e}", subcmd)))?;
    if !status.success() {
        return Err(Error::TraefikLifecycle(format!(
            "docker compose {} exited with {}",
            subcmd.join(" "),
            status.code().unwrap_or(-1),
        )));
    }
    Ok(())
}

async fn compose_capture(compose_file: &Path, subcmd: &[&str]) -> Result<String> {
    let compose_str = compose_file
        .to_str()
        .ok_or_else(|| Error::TraefikLifecycle("compose path not utf-8".into()))?;
    let mut args = vec!["compose", "-f", compose_str];
    args.extend_from_slice(subcmd);
    let output = tokio::process::Command::new("docker")
        .args(&args)
        .output()
        .await
        .map_err(|e| Error::TraefikLifecycle(format!("docker compose {:?}: {e}", subcmd)))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(Error::TraefikLifecycle(format!(
            "docker compose {} failed: {stderr}",
            subcmd.join(" "),
        )));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestResult = std::result::Result<(), Box<dyn std::error::Error>>;

    #[test]
    fn render_static_config_emits_one_entrypoint_per_port() {
        let s = render_static_config(&ProxyConfig {
            ports: vec![3000, 5007],
            dashboard: false,
            docker_api_version: None,
        });
        assert!(s.contains("port-3000:\n"));
        assert!(s.contains("port-5007:\n"));
        assert!(s.contains("address: \":3000\""));
        assert!(s.contains("address: \":5007\""));
        // No dashboard block when disabled.
        assert!(!s.contains("dashboard:\n"));
    }

    #[test]
    fn render_static_config_with_dashboard() {
        let s = render_static_config(&ProxyConfig {
            ports: vec![3000],
            dashboard: true,
            docker_api_version: None,
        });
        // Entry point must be named `traefik` (not `dashboard`) so the
        // auto-router under `api.insecure: true` actually attaches.
        assert!(s.contains("  traefik:\n"));
        assert!(s.contains(&format!("address: \":{DASHBOARD_PORT}\"")));
        assert!(s.contains("api:\n"));
    }

    #[test]
    fn render_compose_publishes_each_port_to_host() {
        let s = render_compose(&ProxyConfig {
            ports: vec![3000, 5007],
            dashboard: false,
            docker_api_version: None,
        });
        assert!(s.contains(&format!("name: {COMPOSE_PROJECT}\n")));
        assert!(s.contains("\"3000:3000\""));
        assert!(s.contains("\"5007:5007\""));
        assert!(s.contains(&format!("name: {PROXY_NETWORK}")));
        // External network keeps compose from fighting `ensure_internal` over
        // ownership labels.
        assert!(s.contains("external: true"));
    }

    #[test]
    fn render_compose_dual_homes_traefik_for_egress() {
        // Traefik must sit on the compose `default` bridge (for its published
        // host ports + egress) AND the `--internal` sandbox-proxy (to route to
        // sandboxes). Published ports don't work on an internal-only network,
        // so dropping `default` would break inbound routing. See ADR-0004.
        let s = render_compose(&ProxyConfig {
            ports: vec![3000],
            dashboard: false,
            docker_api_version: None,
        });
        assert!(s.contains("      - default\n"), "traefik on default bridge");
        assert!(
            s.contains(&format!("      - {PROXY_NETWORK}\n")),
            "traefik on internal sandbox-proxy"
        );
    }

    #[test]
    fn render_compose_with_no_ports_skips_ports_block() {
        let s = render_compose(&ProxyConfig {
            ports: vec![],
            dashboard: false,
            docker_api_version: None,
        });
        assert!(!s.contains("ports:"));
    }

    #[test]
    fn render_compose_does_not_mount_docker_socket() {
        // The file provider replaced the docker provider; the proxy no
        // longer needs the daemon socket. Keeping the socket out is a
        // meaningful security win for the reverse proxy.
        let s = render_compose(&ProxyConfig {
            ports: vec![3000],
            dashboard: false,
            docker_api_version: None,
        });
        assert!(!s.contains("docker.sock"));
        assert!(s.contains("./dynamic:/etc/traefik/dynamic:ro"));
    }

    #[test]
    fn render_writes_both_files_under_proxy_dir() -> TestResult {
        let tmp = tempfile::tempdir()?;
        let cfg = ProxyConfig {
            ports: vec![3000],
            dashboard: true,
            docker_api_version: None,
        };
        let compose = render(tmp.path(), &cfg)?;
        assert!(compose.is_file());
        assert!(tmp.path().join("traefik.yaml").is_file());
        assert!(tmp.path().join("dynamic").is_dir());
        // Compose file points at both the static config and dynamic dir.
        let compose_body = std::fs::read_to_string(&compose)?;
        assert!(compose_body.contains("./traefik.yaml:/etc/traefik/traefik.yaml:ro"));
        assert!(compose_body.contains("./dynamic:/etc/traefik/dynamic:ro"));
        // No docker.sock mount with file provider.
        assert!(!compose_body.contains("docker.sock"));
        Ok(())
    }

    #[test]
    fn render_project_dynamic_one_port() {
        let s = render_project_dynamic("sb-web", "sandbox-abc123", &[3000], "sandbox.localhost");
        assert!(s.contains("    sb-sb-web-3000:\n"));
        assert!(s.contains("rule: \"Host(`sb-web.sandbox.localhost`)\""));
        assert!(s.contains("entryPoints: [\"port-3000\"]"));
        assert!(s.contains("url: \"http://sandbox-abc123:3000\""));
    }

    #[test]
    fn render_project_dynamic_two_ports_two_routers_two_services() {
        let s = render_project_dynamic("api", "sandbox-def", &[3000, 5007], "sandbox.localhost");
        // Two routers, two services, all pointing at the same Host.
        assert_eq!(s.matches("    sb-api-3000:").count(), 2); // once under routers, once under services
        assert_eq!(s.matches("    sb-api-5007:").count(), 2);
        assert!(s.contains("url: \"http://sandbox-def:3000\""));
        assert!(s.contains("url: \"http://sandbox-def:5007\""));
    }

    #[test]
    fn render_project_dynamic_empty_ports_yields_empty_string() {
        assert!(render_project_dynamic("x", "y", &[], "z").is_empty());
    }

    #[test]
    fn write_dynamic_configs_clears_stale_files() -> TestResult {
        let tmp = tempfile::tempdir()?;
        let dyn_dir = tmp.path().join("dynamic");
        std::fs::create_dir_all(&dyn_dir)?;
        // Stale file from a previous run that no longer corresponds to any
        // active project.
        std::fs::write(dyn_dir.join("ghost.yaml"), b"# stale\n")?;

        let projects = vec![(
            "sb-web".to_string(),
            "sandbox-abc".to_string(),
            vec![3000_u16],
        )];
        let written = write_dynamic_configs(tmp.path(), projects, "sandbox.localhost")?;
        assert_eq!(written, vec!["sb-web".to_string()]);
        assert!(dyn_dir.join("sb-web.yaml").is_file());
        // Stale file must be gone.
        assert!(!dyn_dir.join("ghost.yaml").exists());
        Ok(())
    }

    #[test]
    fn write_dynamic_configs_skips_projects_with_no_ports() -> TestResult {
        let tmp = tempfile::tempdir()?;
        let projects = vec![
            ("a".to_string(), "ca".to_string(), vec![3000_u16]),
            ("b".to_string(), "cb".to_string(), vec![]), // no ports → skipped
        ];
        let written = write_dynamic_configs(tmp.path(), projects, "sandbox.localhost")?;
        assert_eq!(written, vec!["a".to_string()]);
        Ok(())
    }
}
